TARGET = libyajl
DLLIB = $(TARGET).bundle
all:

install:
	mkdir -p /Users/vluther/work/ops/oh-my-zsh/.gems/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/lib
	cp $(DLLIB) /Users/vluther/work/ops/oh-my-zsh/.gems/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/lib/$(DLLIB)
	mkdir -p /Users/vluther/work/ops/oh-my-zsh/.gems/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/include/yajl
	cp yajl/*.h /Users/vluther/work/ops/oh-my-zsh/.gems/gems/libyajl2-1.1.0/lib/libyajl2/vendored-libyajl2/include/yajl
