---
driver:
  name: vagrant
  provider: virtualbox
  #require_chef_omnibus: true

provisioner:
  name: chef_solo
  data_bags_path: "./test_data_bags/"

platforms:
  - name: 14.04
    driver:
      box: 1404
suites:
  - name: default
    run_list:
      - recipe[users::sysadmins]
      - recipe[oh-my-zsh::shared]
    attributes:
